apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app-2
  template:
    metadata:
      labels:
        app: python-app-2
    spec:
      containers:
      - name: python-app-2
        image: python-devops-app-2:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
